"use client";

import { motion, useTransform, MotionValue, useSpring } from "framer-motion";

/**
 * A pure CSS/3D-transform MacBook. No WebGL, so it's cheap enough for any
  * phone, but it still folds open exactly in sync with scroll (or stays
   * gently idle when `progress` is a static 0, as in the hero).
    */
    export default function CSSMacBook({
      progress,
        idleFloat = false,
          brandedWhenOpen = true,
          }: {
            progress: MotionValue<number>;
              idleFloat?: boolean;
                brandedWhenOpen?: boolean;
                }) {
                  const smooth = useSpring(progress, { stiffness: 120, damping: 22, mass: 0.6 });

                    // Lid closed ≈ 100deg (folded flat over the base), open ≈ 8deg.
                      const lidRotate = useTransform(smooth, [0, 0.55], [100, 8], { clamp: true });
                        const screenOpacity = useTransform(smooth, [0.45, 0.6], [0, 1]);
                          const wordmarkY = useTransform(smooth, [0.45, 0.6], [6, 0]);
                            const liftY = useTransform(smooth, [0, 0.55, 1], [0, -6, -10]);
                              const scale = useTransform(smooth, [0, 0.55, 1], [0.94, 1, 1.03]);

                                return (
                                    <div
                                          className="relative w-full h-full flex items-center justify-center"
                                                style={{ perspective: "1400px" }}
                                                    >
                                                          <motion.div
                                                                  style={{ y: liftY, scale }}
                                                                          className={idleFloat ? "animate-[macfloat_6s_ease-in-out_infinite]" : ""}
                                                                                >
                                                                                        <div
                                                                                                  className="relative"
                                                                                                            style={{ transformStyle: "preserve-3d", width: "min(72vw, 340px)" }}
                                                                                                                    >
                                                                                                                              {/* Base / keyboard deck */}
                                                                                                                                        <div
                                                                                                                                                    className="relative mx-auto rounded-[3px]"
                                                                                                                                                                style={{
                                                                                                                                                                              width: "100%",
                                                                                                                                                                                            aspectRatio: "16 / 1.1",
                                                                                                                                                                                                          background:
                                                                                                                                                                                                                          "linear-gradient(180deg, #d6d7db 0%, #b7b8bd 55%, #98999f 100%)",
                                                                                                                                                                                                                                        boxShadow: "0 18px 40px -14px rgba(0,0,0,0.65)",
                                                                                                                                                                                                                                                    }}
                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                          <div
                                                                                                                                                                                                                                                                                        className="absolute left-1/2 -translate-x-1/2 top-[2px] rounded-b-sm"
                                                                                                                                                                                                                                                                                                      style={{
                                                                                                                                                                                                                                                                                                                      width: "22%",
                                                                                                                                                                                                                                                                                                                                      height: "55%",
                                                                                                                                                                                                                                                                                                                                                      background: "rgba(0,0,0,0.18)",
                                                                                                                                                                                                                                                                                                                                                                    }}
                                                                                                                                                                                                                                                                                                                                                                                />
                                                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                                                    {/* Lid, hinged at the back edge of the base */}
                                                                                                                                                                                                                                                                                                                                                                                                              <motion.div
                                                                                                                                                                                                                                                                                                                                                                                                                          style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                        rotateX: lidRotate,
                                                                                                                                                                                                                                                                                                                                                                                                                                                      transformOrigin: "50% 100%",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    transformStyle: "preserve-3d",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            className="absolute left-0 right-0 bottom-full mx-auto"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                className="relative mx-auto rounded-t-[10px] rounded-b-[2px] overflow-hidden"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              width: "100%",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              aspectRatio: "16 / 10.2",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              background:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "linear-gradient(160deg, #dcddE0 0%, #aeafb5 45%, #86878d 100%)",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                boxShadow: "0 10px 30px -12px rgba(0,0,0,0.5)",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                padding: "3.5%",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="w-full h-full rounded-[6px] bg-[#050506] flex items-center justify-center relative overflow-hidden">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {/* camera notch */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="absolute top-[6%] left-1/2 -translate-x-1/2 w-[5%] aspect-square rounded-full bg-black ring-1 ring-white/10" />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {brandedWhenOpen && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <motion.span
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              style={{ opacity: screenOpacity, y: wordmarkY }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  className="text-[#f5f4f1] font-sans font-medium tracking-[0.32em] text-[clamp(0.7rem,3vw,1.1rem)]"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        POSTIZ
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </motion.span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </motion.div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </motion.div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }